export const WORKPOOL_STATE_DIR_ENV = "OMO_WORKPOOL_STATE_DIR"
export const WORKPOOL_TASK_ID_ENV = "OMO_WORKPOOL_TASK_ID"
export const WORKPOOL_PROCESS_ENV_NAMES = [WORKPOOL_STATE_DIR_ENV, WORKPOOL_TASK_ID_ENV] as const
